bing_search:
  end_point: https://api.bing.microsoft.com
  subscription_key:
  result_count: 5
openai_api:
  api_key:
  model: text-babbage-001
#  model: text-curie-001
#  model: text-davinci-001
  max_tokens: 150
  temperature: 1
  top_p: 1