bing_search:
  end_point: https://api.bing.microsoft.com
  subscription_key:
  result_count: 5
  text_extract: trafilatura # beautifulsoup
openai_api:
  api_key:
#  model: text-babbage-001
  model: text-curie-001
#  model: text-davinci-001
  max_tokens: 300
  temperature: 1
  top_p: 1
  prompt:
    prompt_length_limit: 3000